// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEYRİ_ALA.Data;

#nullable disable

namespace SEYRİ_ALA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220123215_FinalCitySeedData")]
    partial class FinalCitySeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SEYRİ_ALA.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodScore")
                        .HasColumnType("int");

                    b.Property<int>("HistoryScore")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NatureScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Türkiye'nin kalbi, Cumhuriyet'in başkenti ve Anıtkabir'in evi.",
                            FoodScore = 8,
                            HistoryScore = 10,
                            Latitude = 39.933399999999999,
                            Longitude = 32.859699999999997,
                            Name = "Ankara",
                            NatureScore = 6
                        },
                        new
                        {
                            Id = 2,
                            Description = "İki kıtanın buluştuğu, tarihin kalbi İstanbul.",
                            FoodScore = 10,
                            HistoryScore = 10,
                            Latitude = 41.008200000000002,
                            Longitude = 28.978400000000001,
                            Name = "İstanbul",
                            NatureScore = 5
                        },
                        new
                        {
                            Id = 3,
                            Description = "Peri bacaları ve sıcak hava balonlarıyla masalsı bir yolculuk.",
                            FoodScore = 7,
                            HistoryScore = 9,
                            Latitude = 38.643099999999997,
                            Longitude = 34.828899999999997,
                            Name = "Kapadokya",
                            NatureScore = 10
                        },
                        new
                        {
                            Id = 4,
                            Description = "Masmavi deniz ve antik kentlerin buluşma noktası.",
                            FoodScore = 8,
                            HistoryScore = 8,
                            Latitude = 36.884099999999997,
                            Longitude = 30.7056,
                            Name = "Antalya",
                            NatureScore = 9
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sümela Manastırı ve Uzungöl ile doğanın yeşil tonları.",
                            FoodScore = 9,
                            HistoryScore = 8,
                            Latitude = 41.002699999999997,
                            Longitude = 39.716799999999999,
                            Name = "Trabzon",
                            NatureScore = 10
                        });
                });

            modelBuilder.Entity("SEYRİ_ALA.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SEYRİ_ALA.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("SEYRİ_ALA.Models.TravelRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MapGeoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("SEYRİ_ALA.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SEYRİ_ALA.Models.Comment", b =>
                {
                    b.HasOne("SEYRİ_ALA.Models.TravelRoute", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEYRİ_ALA.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SEYRİ_ALA.Models.Favorite", b =>
                {
                    b.HasOne("SEYRİ_ALA.Models.TravelRoute", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEYRİ_ALA.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SEYRİ_ALA.Models.TravelRoute", b =>
                {
                    b.HasOne("SEYRİ_ALA.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
