// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEYRİ_ALA.Data;

#nullable disable

namespace SEYRİ_ALA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SEYRİ_ALA.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodScore")
                        .HasColumnType("int");

                    b.Property<int>("HistoryScore")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NatureScore")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lezzet ve festivallerin şehri.",
                            FoodScore = 10,
                            HistoryScore = 7,
                            Latitude = 36.991399999999999,
                            Longitude = 35.330800000000004,
                            Name = "Adana",
                            NatureScore = 6,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nemrut Dağı ve dev heykeller.",
                            FoodScore = 7,
                            HistoryScore = 10,
                            Latitude = 37.764800000000001,
                            Longitude = 38.278599999999997,
                            Name = "Adıyaman",
                            NatureScore = 7,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Termal başkent ve mermerin merkezi.",
                            FoodScore = 9,
                            HistoryScore = 8,
                            Latitude = 38.750700000000002,
                            Longitude = 30.556699999999999,
                            Name = "Afyonkarahisar",
                            NatureScore = 6,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 4,
                            Description = "İshak Paşa Sarayı ve heybetli Ağrı Dağı.",
                            FoodScore = 6,
                            HistoryScore = 9,
                            Latitude = 39.721699999999998,
                            Longitude = 43.056699999999999,
                            Name = "Ağrı",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Şehzadeler şehri ve Kralkaya mezarları.",
                            FoodScore = 8,
                            HistoryScore = 10,
                            Latitude = 40.649900000000002,
                            Longitude = 35.835299999999997,
                            Name = "Amasya",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Türkiye'nin kalbi ve Cumhuriyet'in merkezi.",
                            FoodScore = 8,
                            HistoryScore = 10,
                            Latitude = 39.933399999999999,
                            Longitude = 32.859699999999997,
                            Name = "Ankara",
                            NatureScore = 6,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Masmavi deniz ve antik kentler.",
                            FoodScore = 8,
                            HistoryScore = 9,
                            Latitude = 36.896900000000002,
                            Longitude = 30.7133,
                            Name = "Antalya",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Yeryüzü cenneti karagöller ve yaylalar.",
                            FoodScore = 7,
                            HistoryScore = 5,
                            Latitude = 41.1828,
                            Longitude = 41.818300000000001,
                            Name = "Artvin",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Efeler diyarı ve incirin anavatanı.",
                            FoodScore = 8,
                            HistoryScore = 9,
                            Latitude = 37.8444,
                            Longitude = 27.845800000000001,
                            Name = "Aydın",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Ege ve Marmara'nın buluştuğu nokta.",
                            FoodScore = 8,
                            HistoryScore = 7,
                            Latitude = 39.648400000000002,
                            Longitude = 27.8826,
                            Name = "Balıkesir",
                            NatureScore = 9,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Osmanlı'nın kurulduğu topraklar.",
                            FoodScore = 6,
                            HistoryScore = 10,
                            Latitude = 40.142600000000002,
                            Longitude = 29.979299999999999,
                            Name = "Bilecik",
                            NatureScore = 7,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Yüzen adalar ve doğa harikaları.",
                            FoodScore = 7,
                            HistoryScore = 4,
                            Latitude = 38.885399999999997,
                            Longitude = 40.497999999999998,
                            Name = "Bingöl",
                            NatureScore = 9,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Beş minareli şehir ve Ahlat Selçuklu mezarları.",
                            FoodScore = 7,
                            HistoryScore = 10,
                            Latitude = 38.400599999999997,
                            Longitude = 42.109499999999997,
                            Name = "Bitlis",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Abant ve Yedigöller ile doğa tutkusu.",
                            FoodScore = 9,
                            HistoryScore = 5,
                            Latitude = 40.731000000000002,
                            Longitude = 31.608000000000001,
                            Name = "Bolu",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Türkiye'nin Maldivleri: Salda Gölü.",
                            FoodScore = 6,
                            HistoryScore = 8,
                            Latitude = 37.720300000000002,
                            Longitude = 30.290800000000001,
                            Name = "Burdur",
                            NatureScore = 9,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Osmanlı'nın ilk başkenti ve Uludağ.",
                            FoodScore = 10,
                            HistoryScore = 10,
                            Latitude = 40.182400000000001,
                            Longitude = 29.066700000000001,
                            Name = "Bursa",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Destanlar şehri ve Truva antik kenti.",
                            FoodScore = 8,
                            HistoryScore = 10,
                            Latitude = 40.145099999999999,
                            Longitude = 26.406700000000001,
                            Name = "Çanakkale",
                            NatureScore = 9,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Tuz mağaraları ve yarenler diyarı.",
                            FoodScore = 7,
                            HistoryScore = 7,
                            Latitude = 40.601300000000002,
                            Longitude = 33.613399999999999,
                            Name = "Çankırı",
                            NatureScore = 7,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Hattuşaş ile Hititlerin kadim başkenti.",
                            FoodScore = 8,
                            HistoryScore = 10,
                            Latitude = 40.550600000000003,
                            Longitude = 34.955599999999997,
                            Name = "Çorum",
                            NatureScore = 6,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Pamukkale travertenleri ve horozu.",
                            FoodScore = 7,
                            HistoryScore = 9,
                            Latitude = 37.776499999999999,
                            Longitude = 29.086400000000001,
                            Name = "Denizli",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Tarihi surlar ve Hevsel Bahçeleri.",
                            FoodScore = 10,
                            HistoryScore = 10,
                            Latitude = 37.914400000000001,
                            Longitude = 40.210999999999999,
                            Name = "Diyarbakır",
                            NatureScore = 7,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Selimiye Camii ve Kırkpınar güreşleri.",
                            FoodScore = 9,
                            HistoryScore = 10,
                            Latitude = 41.6768,
                            Longitude = 26.556999999999999,
                            Name = "Edirne",
                            NatureScore = 6,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Harput Kalesi ve Gakkoşlar diyarı.",
                            FoodScore = 9,
                            HistoryScore = 9,
                            Latitude = 38.680999999999997,
                            Longitude = 39.226399999999998,
                            Name = "Elazığ",
                            NatureScore = 7,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Doğa sporları ve tulum peyniri.",
                            FoodScore = 8,
                            HistoryScore = 6,
                            Latitude = 39.75,
                            Longitude = 39.5,
                            Name = "Erzincan",
                            NatureScore = 9,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Palandöken ve Çifte Minareli Medrese.",
                            FoodScore = 9,
                            HistoryScore = 9,
                            Latitude = 39.904299999999999,
                            Longitude = 41.267899999999997,
                            Name = "Erzurum",
                            NatureScore = 9,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Porsuk Çayı ve öğrenci kenti.",
                            FoodScore = 8,
                            HistoryScore = 8,
                            Latitude = 39.776699999999998,
                            Longitude = 30.520600000000002,
                            Name = "Eskişehir",
                            NatureScore = 7,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Dünya gastronomi şehri ve Zeugma.",
                            FoodScore = 10,
                            HistoryScore = 10,
                            Latitude = 37.066200000000002,
                            Longitude = 37.383299999999998,
                            Name = "Gaziantep",
                            NatureScore = 5,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Fındığın başkenti ve Giresun Adası.",
                            FoodScore = 8,
                            HistoryScore = 6,
                            Latitude = 40.912799999999997,
                            Longitude = 38.389499999999998,
                            Name = "Giresun",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Karaca Mağarası ve pestil-köme.",
                            FoodScore = 7,
                            HistoryScore = 6,
                            Latitude = 40.460799999999999,
                            Longitude = 39.481400000000001,
                            Name = "Gümüşhane",
                            NatureScore = 9,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Cilo Dağları ve el değmemiş doğa.",
                            FoodScore = 6,
                            HistoryScore = 5,
                            Latitude = 37.574399999999997,
                            Longitude = 43.7408,
                            Name = "Hakkari",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Medeniyetler sofrası ve mozaik müzesi.",
                            FoodScore = 10,
                            HistoryScore = 10,
                            Latitude = 36.202300000000001,
                            Longitude = 36.160600000000002,
                            Name = "Hatay",
                            NatureScore = 7,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Gül ve lavanta bahçeleri.",
                            FoodScore = 7,
                            HistoryScore = 7,
                            Latitude = 37.764400000000002,
                            Longitude = 30.5519,
                            Name = "Isparta",
                            NatureScore = 9,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Palmiyeler, liman ve Tantuni.",
                            FoodScore = 9,
                            HistoryScore = 8,
                            Latitude = 36.812100000000001,
                            Longitude = 34.641500000000001,
                            Name = "Mersin",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 34,
                            Description = "İki kıtanın birleştiği dünya mirası.",
                            FoodScore = 10,
                            HistoryScore = 10,
                            Latitude = 41.008200000000002,
                            Longitude = 28.978400000000001,
                            Name = "İstanbul",
                            NatureScore = 6,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Ege'nin incisi ve Efes antik kenti.",
                            FoodScore = 9,
                            HistoryScore = 10,
                            Latitude = 38.419199999999996,
                            Longitude = 27.128699999999998,
                            Name = "İzmir",
                            NatureScore = 9,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Ani Harabeleri ve kar altındaki tarih.",
                            FoodScore = 9,
                            HistoryScore = 10,
                            Latitude = 40.601900000000001,
                            Longitude = 43.097499999999997,
                            Name = "Kars",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Valla Kanyonu ve tarihi konaklar.",
                            FoodScore = 8,
                            HistoryScore = 8,
                            Latitude = 41.378700000000002,
                            Longitude = 33.7744,
                            Name = "Kastamonu",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Erciyes Dağı ve pastırmanın merkezi.",
                            FoodScore = 10,
                            HistoryScore = 8,
                            Latitude = 38.720500000000001,
                            Longitude = 35.482599999999998,
                            Name = "Kayseri",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Longoz ormanları ve sakinlik.",
                            FoodScore = 7,
                            HistoryScore = 6,
                            Latitude = 41.735100000000003,
                            Longitude = 27.226099999999999,
                            Name = "Kırklareli",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Ahi Evran diyarı ve ozanlar şehri.",
                            FoodScore = 7,
                            HistoryScore = 8,
                            Latitude = 39.142499999999998,
                            Longitude = 34.170900000000003,
                            Name = "Kırşehir",
                            NatureScore = 6,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Sanayi ve Kartepe kayak merkezi.",
                            FoodScore = 7,
                            HistoryScore = 6,
                            Latitude = 40.853299999999997,
                            Longitude = 29.881499999999999,
                            Name = "Kocaeli",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Mevlana ve hoşgörü şehri.",
                            FoodScore = 9,
                            HistoryScore = 10,
                            Latitude = 37.871400000000001,
                            Longitude = 32.4846,
                            Name = "Konya",
                            NatureScore = 7,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Çini ve porselen sanatı.",
                            FoodScore = 7,
                            HistoryScore = 9,
                            Latitude = 39.419699999999999,
                            Longitude = 29.985700000000001,
                            Name = "Kütahya",
                            NatureScore = 7,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Kayısının başkenti ve Aslantepe Höyüğü.",
                            FoodScore = 9,
                            HistoryScore = 9,
                            Latitude = 38.355200000000004,
                            Longitude = 38.3095,
                            Name = "Malatya",
                            NatureScore = 7,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Şehzadeler şehri ve Mesir Macunu.",
                            FoodScore = 8,
                            HistoryScore = 9,
                            Latitude = 38.619100000000003,
                            Longitude = 27.428899999999999,
                            Name = "Manisa",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Dondurma ve kurtuluş mücadelesi.",
                            FoodScore = 10,
                            HistoryScore = 8,
                            Latitude = 37.575299999999999,
                            Longitude = 36.922800000000002,
                            Name = "Kahramanmaraş",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Taş konaklar ve masalsı tarih.",
                            FoodScore = 9,
                            HistoryScore = 10,
                            Latitude = 37.312899999999999,
                            Longitude = 40.733899999999998,
                            Name = "Mardin",
                            NatureScore = 6,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Bodrum, Marmaris ve eşsiz koylar.",
                            FoodScore = 8,
                            HistoryScore = 9,
                            Latitude = 37.215299999999999,
                            Longitude = 28.363600000000002,
                            Name = "Muğla",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Malazgirt Ovası ve tarihi camiler.",
                            FoodScore = 6,
                            HistoryScore = 8,
                            Latitude = 38.743200000000002,
                            Longitude = 41.506399999999999,
                            Name = "Muş",
                            NatureScore = 7,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Kapadokya ve peri bacaları.",
                            FoodScore = 7,
                            HistoryScore = 10,
                            Latitude = 38.624400000000001,
                            Longitude = 34.714399999999998,
                            Name = "Nevşehir",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 51,
                            Description = "Aladağlar ve tarihi kiliseler.",
                            FoodScore = 7,
                            HistoryScore = 8,
                            Latitude = 37.966700000000003,
                            Longitude = 34.683300000000003,
                            Name = "Niğde",
                            NatureScore = 9,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 52,
                            Description = "Boztepe'den Karadeniz manzarası.",
                            FoodScore = 8,
                            HistoryScore = 6,
                            Latitude = 40.983899999999998,
                            Longitude = 37.876399999999997,
                            Name = "Ordu",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Çayın merkezi ve kaçkar yaylaları.",
                            FoodScore = 8,
                            HistoryScore = 5,
                            Latitude = 41.020099999999999,
                            Longitude = 40.523400000000002,
                            Name = "Rize",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Sapanca Gölü ve doğa tatili.",
                            FoodScore = 8,
                            HistoryScore = 5,
                            Latitude = 40.756900000000002,
                            Longitude = 30.378900000000002,
                            Name = "Sakarya",
                            NatureScore = 9,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Milli mücadelenin başladığı şehir.",
                            FoodScore = 8,
                            HistoryScore = 9,
                            Latitude = 41.2928,
                            Longitude = 36.331299999999999,
                            Name = "Samsun",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Tillo ve büryan kebabı.",
                            FoodScore = 9,
                            HistoryScore = 8,
                            Latitude = 37.933300000000003,
                            Longitude = 41.933300000000003,
                            Name = "Siirt",
                            NatureScore = 7,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 57,
                            Description = "Türkiye'nin en kuzey noktası ve mantı.",
                            FoodScore = 9,
                            HistoryScore = 9,
                            Latitude = 42.023099999999999,
                            Longitude = 35.153100000000002,
                            Name = "Sinop",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 58,
                            Description = "Selçuklu mimarisi ve Divriği Ulu Camii.",
                            FoodScore = 8,
                            HistoryScore = 10,
                            Latitude = 39.747700000000002,
                            Longitude = 37.017899999999997,
                            Name = "Sivas",
                            NatureScore = 7,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 59,
                            Description = "Köfte ve deniz havası.",
                            FoodScore = 9,
                            HistoryScore = 6,
                            Latitude = 40.9833,
                            Longitude = 27.5167,
                            Name = "Tekirdağ",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 60,
                            Description = "Ballıca Mağarası ve Tokat Kebabı.",
                            FoodScore = 9,
                            HistoryScore = 9,
                            Latitude = 40.316699999999997,
                            Longitude = 36.549999999999997,
                            Name = "Tokat",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 61,
                            Description = "Sümela Manastırı ve horon.",
                            FoodScore = 9,
                            HistoryScore = 9,
                            Latitude = 41.002699999999997,
                            Longitude = 39.716799999999999,
                            Name = "Trabzon",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 62,
                            Description = "Munzur Vadisi ve doğal yaşam.",
                            FoodScore = 7,
                            HistoryScore = 5,
                            Latitude = 39.107900000000001,
                            Longitude = 39.540100000000002,
                            Name = "Tunceli",
                            NatureScore = 10,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 63,
                            Description = "Göbeklitepe ve Balıklıgöl.",
                            FoodScore = 10,
                            HistoryScore = 10,
                            Latitude = 37.159100000000002,
                            Longitude = 38.796900000000001,
                            Name = "Şanlıurfa",
                            NatureScore = 6,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 64,
                            Description = "Karun Hazineleri ve kanyonlar.",
                            FoodScore = 7,
                            HistoryScore = 9,
                            Latitude = 38.682299999999998,
                            Longitude = 29.408200000000001,
                            Name = "Uşak",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 65,
                            Description = "Van Gölü ve Akdamar Adası.",
                            FoodScore = 9,
                            HistoryScore = 9,
                            Latitude = 38.489100000000001,
                            Longitude = 43.408900000000003,
                            Name = "Van",
                            NatureScore = 9,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 66,
                            Description = "Türkiye'nin ilk milli parkı.",
                            FoodScore = 8,
                            HistoryScore = 7,
                            Latitude = 39.818100000000001,
                            Longitude = 34.814700000000002,
                            Name = "Yozgat",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 67,
                            Description = "Emeğin başkenti ve mağaralar.",
                            FoodScore = 7,
                            HistoryScore = 5,
                            Latitude = 41.456400000000002,
                            Longitude = 31.7987,
                            Name = "Zonguldak",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 68,
                            Description = "Ihlara Vadisi ve kervansaraylar.",
                            FoodScore = 7,
                            HistoryScore = 9,
                            Latitude = 38.368699999999997,
                            Longitude = 34.032200000000003,
                            Name = "Aksaray",
                            NatureScore = 9,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 69,
                            Description = "Baksı Müzesi ve Çoruh Nehri.",
                            FoodScore = 6,
                            HistoryScore = 7,
                            Latitude = 40.255200000000002,
                            Longitude = 40.224899999999998,
                            Name = "Bayburt",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 70,
                            Description = "Türkçe'nin başkenti.",
                            FoodScore = 7,
                            HistoryScore = 9,
                            Latitude = 37.175899999999999,
                            Longitude = 33.228700000000003,
                            Name = "Karaman",
                            NatureScore = 6,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 71,
                            Description = "Silah sanayi ve MKE.",
                            FoodScore = 6,
                            HistoryScore = 5,
                            Latitude = 39.846800000000002,
                            Longitude = 33.515300000000003,
                            Name = "Kırıkkale",
                            NatureScore = 6,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 72,
                            Description = "Hasankeyf ve petrol şehri.",
                            FoodScore = 7,
                            HistoryScore = 9,
                            Latitude = 37.8812,
                            Longitude = 41.135100000000001,
                            Name = "Batman",
                            NatureScore = 7,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 73,
                            Description = "Cudi Dağı ve Nuh'un Gemisi izleri.",
                            FoodScore = 6,
                            HistoryScore = 8,
                            Latitude = 37.516399999999997,
                            Longitude = 42.461100000000002,
                            Name = "Şırnak",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 74,
                            Description = "Amasra ve tarihi evler.",
                            FoodScore = 8,
                            HistoryScore = 8,
                            Latitude = 41.634399999999999,
                            Longitude = 32.337499999999999,
                            Name = "Bartın",
                            NatureScore = 9,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 75,
                            Description = "Çıldır Gölü ve soğuk hava.",
                            FoodScore = 7,
                            HistoryScore = 6,
                            Latitude = 41.110500000000002,
                            Longitude = 42.702199999999998,
                            Name = "Ardahan",
                            NatureScore = 9,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 76,
                            Description = "Üç ülkeye komşu ve kayısı.",
                            FoodScore = 7,
                            HistoryScore = 5,
                            Latitude = 39.923699999999997,
                            Longitude = 44.045000000000002,
                            Name = "Iğdır",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 77,
                            Description = "Termal sular ve doğa.",
                            FoodScore = 7,
                            HistoryScore = 6,
                            Latitude = 40.654899999999998,
                            Longitude = 29.273800000000001,
                            Name = "Yalova",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 78,
                            Description = "Safranbolu evleri.",
                            FoodScore = 8,
                            HistoryScore = 10,
                            Latitude = 41.206099999999999,
                            Longitude = 32.620399999999997,
                            Name = "Karabük",
                            NatureScore = 8,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 79,
                            Description = "Üzüm bağları ve kebap.",
                            FoodScore = 9,
                            HistoryScore = 7,
                            Latitude = 36.718400000000003,
                            Longitude = 37.121200000000002,
                            Name = "Kilis",
                            NatureScore = 6,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 80,
                            Description = "Yer fıstığı ve kaleler şehri.",
                            FoodScore = 8,
                            HistoryScore = 8,
                            Latitude = 37.074199999999998,
                            Longitude = 36.246699999999997,
                            Name = "Osmaniye",
                            NatureScore = 7,
                            Region = "Tümü"
                        },
                        new
                        {
                            Id = 81,
                            Description = "Şelaleler ve rafting merkezi.",
                            FoodScore = 8,
                            HistoryScore = 5,
                            Latitude = 40.843800000000002,
                            Longitude = 31.156500000000001,
                            Name = "Düzce",
                            NatureScore = 10,
                            Region = "Tümü"
                        });
                });

            modelBuilder.Entity("SEYRİ_ALA.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("SEYRİ_ALA.Models.TravelRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MapGeoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("SEYRİ_ALA.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.HasOne("SEYRİ_ALA.Models.City", "City")
                        .WithMany("Comments")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEYRİ_ALA.Models.TravelRoute", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId");

                    b.HasOne("SEYRİ_ALA.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SEYRİ_ALA.Models.Favorite", b =>
                {
                    b.HasOne("SEYRİ_ALA.Models.City", "City")
                        .WithMany("Favorites")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEYRİ_ALA.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SEYRİ_ALA.Models.TravelRoute", b =>
                {
                    b.HasOne("SEYRİ_ALA.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("SEYRİ_ALA.Models.City", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
